spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: ${MONGODB_URL}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: guest
    password: guest
    listener:
      simple:
        auto-startup: true
springdoc:
  packages-to-scan: kbe.breakinpedia.warehouseservice.controller
  api-docs:
    path: /warehouse-api
server:
  port: 8082
