spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: ${MONGODB_URL}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: guest
    password: guest
#    listener:
#      simple:
#        auto-startup: true
springdoc:
  packages-to-scan: kbe.breakinpedia.paymentservice.controller
  api-docs:
    path: /payment-api
server:
  port: 8084